version: "3.8"
volumes:
  db-data:
    driver: local

services:
  app:
    build:
      context: .
    environment:
      - spring.profiles.active=prod
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
      - MYSQL_DATABASE=url-shortener
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 --user=$MYSQL_USER --password=$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

