spring:
  datasource:
    url: jdbc:h2:mem:./url-shortener
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: info