spring:
  datasource:
    url: jdbc:mysql://mysql:3306/url-shortener
    username: user
    password: pwd

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true

  kafka:
    bootstrap-servers:
      - kafka1:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 0


rest:
  output:
    max-clicks-number: 200

debug: false