spring:
  datasource:
    url: jdbc:mysql://mysql:3306/url-shortener
    username: user
    password: pwd

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
rest:
  output:
    max-clicks-number: 200

debug: false