spring:
  profiles:
    active: dev
  web:
    locale: en_US

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:./url-shortener
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop

hibernate:
  dialect: org.hibernate.dialect.H2Dialect

---

spring:
  config:
    activate:
      on-profile: prod

rest:
  output:
    max-clicks-number: 200

debug: false
