spring:
  datasource:
    url: jdbc:mysql://mysql:3306/url-shortener
    username: user
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
rest:
  output:
    max-clicks-number: 200

logging:
  level:
    root: debug

debug: false